version: '3'
services:
  client:
    image: codeveloper-frontend-image
    stdin_open: true  
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    networks:
      - codeveloper-network
    depends_on:
      - server
  server:
    image: codeveloper-backend-image
    build: ./server/
    ports:
      - '5000:5000'
    networks:
      - codeveloper-network
    depends_on:
      - db
  db:
    image: 'mongo:4.2'
    networks:
      - codeveloper-network
    volumes:
      - mongodb:/data/db
    ports:
      - '27017:27017'
volumes:
  mongodb:
    driver: local
networks:
 codeveloper-network: {
  driver: bridge
 }
