version: '3'
services:
  nginx :
    image : 820345296460.dkr.ecr.us-east-1.amazonaws.com/codeveloper-nginx-image
    ports :
      - '80:80'
    networks:
      - codeveloper-network
    depends_on :
      - client
      - server
  client:
    image : 820345296460.dkr.ecr.us-east-1.amazonaws.com/codeveloper-frontend-image
    restart: always
    # ports:
    #   - '3000:3000'
    container_name: client
    networks:
      - codeveloper-network
    depends_on:
      - server
    environment:
      - WDS_SOCKET_PORT=0
      - WDS_SOCKET_HOST=0.0.0.0
  server:
    image : 820345296460.dkr.ecr.us-east-1.amazonaws.com/codeveloper-backend-image
    restart: always
    # ports:
    #   - '5000:5000'
    container_name: server
    networks:
      - codeveloper-network
networks:
 codeveloper-network: {
  driver: bridge
 }
