version: '3'
services:
  client:
    image: codeveloper-frontend-image
    build: 
      context: ./client/
      dockerfile: Dockerfile.dev
    stdin_open: true  
    ports:
      - '3000:3000'
    networks:
      - codeveloper-network
    depends_on:
      - server
  server:
    image: codeveloper-backend-image
    build: ./server/
    ports:
      - '5000:5000'
    networks:
      - codeveloper-network
networks:
 codeveloper-network: {
  driver: bridge
 }
